// <auto-generated />
namespace Anderson.MF7.Infra.ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class vinitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vinitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201808312022488_v.initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
